### ISSUE TITLE
Get cant find Shares when running script from cron

### ISSUE THREAD

**Issue by a2liter** [droboports/crond#1]
I have a PHP script that i am running as root on the drobo. It works perfectly from the command line but when it tries to run from cron I get the following error

crond: USER root pid 21505 cmd \* /mnt/DroboFS/Shares/DroboApps/php5/bin/php -f /mnt/DroboFS/scripts/movemkv
/bin/sh: Shares: not found

Can anyone help me with why this is happening? I have tried just about all the things I can think of.

**Comment by ricardopadilha** [comment]
I'm sorry, this is not a general support forum for crond. If you have an issue with the packaging of crond as a DroboApp, please reopen this issue. I suggest reading [crontab's man page](http://linux.die.net/man/5/crontab) for more information about configuring crond. You seem to have a globbing problem, coupled with a quoting problem. [This](http://stackoverflow.com/questions/15670396/shell-glob-expansion-with-spaces) might also be of interest.

**Comment by a2liter** [comment]
It is not a problem with cron... it is trying to fire... I created a very simple script that has nothing to do with Shares or directories with spaces and I am still getting the same error.

Here is about a simple of a scupt that I can test with... it just write woot to a log file in /var/log

<?php
 date_default_timezone_set('America/New_York');
 $h=fopen("/var/log/movemkv","a+");
 fwrite($h,("woot\n\n"));
 fclose($h);
?>

When cron tries to fire this one I still get the same error.
